### ISSUE TITLE
Cache Inclusion for Post IDs or remove cache for logged_in users and add exlusions?

### ISSUE THREAD

**Issue by sissibieber** [keycdn/cache-enabler#130]
We are running a WooCommerce shop with different price groups (defined by roles). When a user is logged in the cache is disabled, which is fine, especially for product pages. But we have some (only) content pages which we would like to be served by the cache. 
The question now, should we remove the regex for "disable cache" for logged_in users and then add the shop pages to the cache exclusion list (e.g. overview page, cart, checkout, products, ...) or would it be useful to add a specific cache inclusion option for page/post IDs? 

Whats the best practice here?

**Comment by coreykn** [comment]
Thanks for reaching out. It feels like this is a question that would be better suited in the [Cache Enabler Support Forum](https://wordpress.org/support/plugin/cache-enabler/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the reposted question (so that other people can find it) or add some more details if you feel this is a genuine bug report or enhancement request.

**Comment by sissibieber** [comment]
hey @coreykn - thanks for the feedback, that makes definitely sense. During writing I changed my first idea of a feature request to keep it an open question, because I am just not sure about it. 
Link to [support forum](https://wordpress.org/support/topic/best-practice-wc-with-different-pricing-structure-and-caching/)
