### ISSUE TITLE
New cache system question

### ISSUE THREAD

**Issue by BWBama85** [keycdn/cache-enabler#150]
We have scripts that update our content via APIs. With the new cache system, will the cache be cleared if we call wp_update_post() to update these posts?

**Comment by coreykn** [comment]
Thanks for reaching out. It feels like this is a support-related question and would be better suited in the [Cache Enabler Support Forum](https://wordpress.org/support/plugin/cache-enabler/). We prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the reposted question (so that other people can find it) or add some more details if you feel this is a genuine bug report or enhancement request.
