### ISSUE TITLE
different cache dir

### ISSUE THREAD

**Issue by monmonja** [keycdn/cache-enabler#174]
is there a way (besides manually editing)  to configure Cache_Enabler_Disk::$cache_dir to a different directory?

**Comment by coreykn** [comment]
Not that I'm aware of. A filter wasn't added here in the recent hook updates introduced in version 1.6.0 due to when this variable is called, which at the earliest would be on the `advanced-cache.php` drop-in. As far as I know that means even if a filter was added it would not be registered so filtered data would not be returned and applied.
