### ISSUE TITLE
Cache Enabler does not detect WP_CACHE Constant

### ISSUE THREAD

**Issue by planetahuevo** [keycdn/cache-enabler#178]
Hi, 
I am using an include on my wp_config and there is where I load the WP_CACHE constant.
Cache enabler looks into the wp-config file instead of checking for the constant to be set:
https://github.com/keycdn/cache-enabler/blob/47d7fa54f91a7d3709a59291b92d1e74472f3efe/inc/cache_enabler_disk.class.php#L921

And then it show the message on the dashboard. 
But the message is wrong, because it is defined and it is set as True.

I think that the function "set_wp_cache_constant" should check for the constant to be defined in the first place, before to start messing with the files. 
Thanks

**Comment by coreykn** [comment]
Just so you're aware this topic has been discussed a few times in detail already. The warning itself is only displayed if the `WP_CACHE` constant is `false`:

https://github.com/keycdn/cache-enabler/blob/3bc69e84933aa371477d1164df20877da59754ba/inc/cache_enabler.class.php#L1603-L1613

Cache Enabler does not rely on the `WP_CACHE` constant being set in the `wp-config.php` file. The `WP_CACHE` constant is used for including the `advanced-cache.php` drop-in when `true`. This is a primary file that Cache Enabler requires to cache and deliver pages. The snippet you've mentioned is only related to when Cache Enabler actually sets or unsets the `WP_CACHE` constant in the `wp-config.php` file. Currently Cache Enabler will only set this if not already defined and if the plugin believes the `wp-config.php` file is the default (instead of a custom config file like when using Bedrock). The issue you're experiencing does not sound like its related to how Cache Enabler sets this constant.

If you still receive that warning it either indicates `WP_CACHE` is still `false`, which can be confirmed if your pages are not being cached and delivered, or an unlikely case would be that your admin pages are being cached by your browser. If your pages are not being cached and delivered please ensure `WP_CACHE` is defined before WordPress sets up its vars and included files. If your pages are being cached and delivered please ensure your admin pages are not being cached by your browser, which is handled through the `Cache-Control` response header.

**Comment by planetahuevo** [comment]
You are completely right. 
That makes more sense. 
Not sure why my setup is not getting the WP_CACHE, but it is clearly my installation problem and nothing with your plugin.
Thank you for your time and for the nice notification, that helped me to detect the issue.

**Comment by coreykn** [comment]
You're welcome, happy to know I was able to help. 🙂
