### ISSUE TITLE
Preloading HTML Caching

### ISSUE THREAD

**Issue by thegulshankumar** [keycdn/cache-enabler#182]
Dear,

An optional checkbox for XML Sitemap based Preloading would be great.

Slowly, to avoid overload on low-end server
- 1 request per 4 seconds

Thanks & Regards,
Gulshan

**Comment by PepinoGz** [comment]
Yes please, we need it!

**Comment by davelit** [comment]
You could use the [Warm Cache](https://wordpress.org/plugins/warm-cache/) plugin. However, I think WP_CRON based solutions are sub-optimal, as they _increase_ the page load time until the cache is warm and current.

For system cron jobs, I can recommend [Optimus Cache Prime](https://patrickmn.com/projects/ocp/), a hidden gem that hasn't received the recognition it deserves yet.

**Comment by coreykn** [comment]
We have no plans on adding this to Cache Enabler. I think using what has been suggested by @davelit are great options. If anyone else has others please feel free to share.

If this is still wanted once extensions are supported I'd be happy to help provide any guidance needed to add support for it in that way.

**Comment by lockemx** [comment]
OCP works well, but it would be seen as a non-webp client by default. Since I had the plugin's cache configured to vary / split for webp, I needed to make a custom build of OCP. It's a simple golang program with source available, so I mirrored how User-Agent is changed to also change the Accept header with a flag and specified "image/webp".
