### ISSUE TITLE
PHP Warning for CACHE_ENABLER_DIR constant

### ISSUE THREAD

**Issue by UVLabs** [keycdn/cache-enabler#232]
Issue is on this line: https://github.com/keycdn/cache-enabler/blob/master/inc/cache_enabler_disk.class.php#L60

`Use of undefined constant CACHE_ENABLER_DIR - assumed 'CACHE_ENABLER_DIR' (this will throw an Error in a future version of PHP) in /Users/uvdev/Local Sites/skraveshippingdev/app/public/wp-content/plugins/cache-enabler/inc/cache_enabler_disk.class.php on line 60`

This is also causing the plugin to not find and copy the advanced-cache file to wp-content folder:

![image](https://user-images.githubusercontent.com/10324144/114921516-a32cbb00-9df8-11eb-85b2-f0eb3abcf1c9.png)

![image](https://user-images.githubusercontent.com/10324144/114921936-17675e80-9df9-11eb-8090-aacd092a4819.png)

Tested on PHP 7.3 and 7.4.1

**Comment by coreykn** [comment]
I'm unable to replicate this issue when updating the plugin from an old version to 1.7+. The `CACHE_ENABLER_DIR` constant is currently defined in the `cache-enabler.php` file: https://github.com/keycdn/cache-enabler/blob/1.7.1/cache-enabler.php

To troubleshoot this further, please answer the following questions at your convenience:

1. What version did you update from?
2. How was your plugin updated when this occurred?
3. What type of WordPress website do you have? For example, a single or multisite installation.
3. Do you have steps that can be taken to replicate it?

**Comment by UVLabs** [comment]
- Updated from v1.3.5
- Updated from native WP updater in dashboard
- Single site
- I just went to the updates area (not plugins area) and added the plugin to the list to update. After it was done I noticed the error. I tested this on a local env before i did the update on production so I'm not sure if that had anything to do with it but I'm using Local By Flywheel

**Comment by coreykn** [comment]
Thanks for the additional information, @UVLabs. I just ran a few tests updating from v1.3.5 to v1.7.1 in the way you described as well as another and was unable to replicate this issue. This was done both locally and remotely.

As you may already know, [`upgrader_process_complete`](https://developer.wordpress.org/reference/hooks/upgrader_process_complete/), the hook `Cache_Enabler::on_ce_update()` (now `Cache_Enabler::on_cache_enabler_update()` is registered to, does have a caveat as the way we're using it makes it run the old version of the plugin. However, that's the entire old version of the plugin and not just a part of it. For example, that is why `Cache_Enabler::on_ce_update()` was called instead of `Cache_Enabler::on_cache_enabler_update()`. I believe it has been since PR #166 we've fully taken this into account to ensure our updates do what we need.

Unfortunately I'm unsure why this occurred to you and am unable to test with the local solution that you're using. You are the first that I'm aware of that has experienced this issue. In this case I would recommend reinstalling the plugin.

**Comment by coreykn** [comment]
I'm going to close this as I think what occurred to you was just an odd case. However, if you need me to do any further investigating please feel free to open it again.

**Comment by UVLabs** [comment]
@coreykn Ok, I'm going to be updating it on the live site soon, if the issue still occurs then ill just delete the plugin and install from the repo again
