### ISSUE TITLE
Cache purging mechanism...

### ISSUE THREAD

**Issue by erikdemarco** [keycdn/cache-enabler#253]
@coreykn @stevegrunwell This is very very nice idea using cache iterator to clean expired cache via cron here #223 and #237.
But does it scale?

for example a site having hundred thousand of post cached. And the expiry_time set to 1 hour. and php time_limit is set to 30 seconds (php default settings). Will it finish delete all those in those timeframe?

Deleting all those pages at the same time doesn't feel like very friendly solution to server resources.

The standard way of clearing cache (check and clear only when the url requested) is much more friendly to server resources and much more stable. This is also how nginx delete expired content. Nginx has been deployed many years by giant sites. So this way of clearing the cache files dont need to be doubt anymore. It has been battle tested.

Instead of deprecating old way of purging cache. Please make it alternative method. Let the user choose how it handle the purging mechanism for their sites. 1000 sites have 1000 needs. You cant just force all of them using the same method.

**Comment by coreykn** [comment]
@erikdemarco, this is the third duplicate post you've made about this subject in the last 12 hours ([here](https://wordpress.org/support/topic/suggestion-for-max-cache-size-option/#post-14694020) and [here](https://github.com/keycdn/cache-enabler/pull/237#issuecomment-885761943)). We'll always get back to you as soon as we are able, but please allow us enough time to respond. Duplicate posts actually slows down how fast we are able to respond because now we have more to go through. I've replied to your post [here](https://github.com/keycdn/cache-enabler/pull/237#issuecomment-885985470) (happened to working on that reply right before you posted here). We can continue there for now if any more discussion is needed. Thanks.
