### ISSUE TITLE
Version 1.8+ on IIS

### ISSUE THREAD

**Issue by mmojadad** [keycdn/cache-enabler#291]
Hello
Cache for Homepage not generate after upgrade to version 1.8.3 , I tested on IIS, Two different server, The issue just happen on homepage and of course Webp version also not serve.

Regards,

**Comment by coreykn** [comment]
To troubleshoot this issue, can you please send over the Site Health Info for that site along with the direct URL to the website in reference (like done #288)? In this case, providing a screenshot of your Cache Enabler settings would also be helpful.

**Comment by mmojadad** [comment]
@coreykn Done!

**Comment by coreykn** [comment]
Thanks @mmojadad for all of your assistance with troubleshooting this issue. You've been awesome! Updating this thread to share what was happening.

This issue occurred due to the `web.config` file having the following set and the update in PR #260 to the `Cache_Enabler_Engine::is_index()` method:

```xml
<defaultDocument>
    <files>
        <clear />
        <add value="Index.php" />
    </files>
</defaultDocument>
```

The file stored on the server was named "index.php" and not "Index.php". As far as I know Windows file names are not case sensitive unless set otherwise. However, the large majority of servers that Cache Enabler is installed on are. That is why when introducing the `CACHE_ENABLER_INDEX_FILE` constant in 1.8 we no longer force the `$_SERVER['SCRIPT_NAME']` value to be lowercase:
    
* 1.7.2: https://github.com/keycdn/cache-enabler/blob/45db4c70580c3d03f13ec7bc1e627ad2ebc53135/inc/cache_enabler_engine.class.php#L202-L218

* 1.8.4: https://github.com/keycdn/cache-enabler/blob/5f3424bccb3398a978fa3c27e9717b977d1ede5f/inc/cache_enabler_engine.class.php#L182-L207

To fix this the "Index.php" value was updated to "index.php" instead:

```xml
<defaultDocument>
    <files>
        <clear />
        <add value="index.php" />
    </files>
</defaultDocument>
```

I think this is more of an installation issue, but if this becomes an issue for anyone else on an IIS server please let me know and we can make a change.
