### ISSUE TITLE
Undefined index: HTTP_HOST when running wp-cli command that imports products

### ISSUE THREAD

**Issue by sandrodz** [keycdn/cache-enabler#68]
`
PHP Notice:  Undefined index: HTTP_HOST in /var/www/superstore.wearede.com/public/plugins/cache-enabler/inc/cache_enabler_disk.class.php on line 603`

My custom wp-cli command creates WooCommerce product drafts. Why is it triggering delete settings at all?

**Comment by coreykn** [comment]
This occurred because when any post type was saved the [`save_hook`](https://github.com/keycdn/cache-enabler/blob/12563d72d2bb1f5e4c84acad593889a60aeb90cd/inc/cache_enabler.class.php#L125-L131) was being fired. This caused [`Cache_Enabler::check_future_posts()`](https://github.com/keycdn/cache-enabler/blob/12563d72d2bb1f5e4c84acad593889a60aeb90cd/inc/cache_enabler.class.php#L1367-L1388) to be called. If there was not a cache timeout to be recorded [`Cache_Enabler_Disk::delete_advcache_settings()`](https://github.com/keycdn/cache-enabler/blob/12563d72d2bb1f5e4c84acad593889a60aeb90cd/inc/cache_enabler_disk.class.php#L590-L629) was being called.

Improving this behavior ties into #112. I've completed this enhancement and will open a PR shortly. This change will be released in version 1.5.0.
